### ISSUE TITLE
can this library be used on stm32f429?

### ISSUE THREAD

**Issue by CaiNiaoLucifer** [arduino-org/arduino-core-stm32f4#41]
My board is ST nucleo f429.
Thanks & BR

**Comment by fpistm** [comment]
Hi,
No this support f469 (MCU used for the Star Otto).
Support of Nucleo F429ZI will be released soon on stm32duino github.
BR

**Comment by alfran** [comment]
Hi CaiNiaoLucifer,
This Repository support only the Arduino STAR OTTO,
